/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/

import { createRoute } from "route-action-gen/lib/next";
import {
  handler as deleteHandler,
  requestValidator as deleteRequestValidator,
  responseValidator as deleteResponseValidator,
} from "../route.delete.config";

export const DELETE = createRoute(
  deleteRequestValidator,
  deleteResponseValidator,
  deleteHandler,
);
