// @generated by scripts/generate-index.ts -- DO NOT EDIT

import { PasswordForgotEmail, type PasswordForgotEmailProps } from "./user/password-forgot";
import { SignupEmail, type SignupEmailProps } from "./user/signup";

export { PasswordForgotEmail, type PasswordForgotEmailProps };
export { SignupEmail, type SignupEmailProps };

export type TemplateMap = {
  "user/password-forgot": PasswordForgotEmailProps;
  "user/signup": SignupEmailProps;
};

export const templates: {
  [K in keyof TemplateMap]: React.ComponentType<TemplateMap[K]>;
} = {
  "user/password-forgot": PasswordForgotEmail,
  "user/signup": SignupEmail,
};
