/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/

import { createRoute } from "route-action-gen/lib/next";
import {
  handler as getHandler,
  requestValidator as getRequestValidator,
  responseValidator as getResponseValidator,
} from "../route.get.config";
import {
  handler as postHandler,
  requestValidator as postRequestValidator,
  responseValidator as postResponseValidator,
} from "../route.post.config";

export const GET = createRoute(
  getRequestValidator,
  getResponseValidator,
  getHandler
);
export const POST = createRoute(
  postRequestValidator,
  postResponseValidator,
  postHandler
);
