/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/

import { createRoute } from "route-action-gen/lib/next";
import {
  handler as postHandler,
  requestValidator as postRequestValidator,
  responseValidator as postResponseValidator,
} from "../route.post.config";

export const POST = createRoute(
  postRequestValidator,
  postResponseValidator,
  postHandler
);
